version: '3.8'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes: 
       - ~/apps/redis:/var/lib/redis
    restart: on-failure